### ISSUE TITLE
選曲画面で選択中の楽曲の横に印がつく

### ISSUE THREAD

**Issue by WatanabeMasaaki** [K93MSY/DanmakuCat#10]
最初の画面です
下の画像のようにしてみたい
![IMG_0025](https://user-images.githubusercontent.com/86590348/190905979-e6e8bc9e-0dc0-4e52-8890-de89162b7b14.PNG)

**Comment by K93MSY** [comment]
やっときます

**Comment by WatanabeMasaaki** [comment]
ありがとう！
