### ISSUE TITLE
名前の変更　DanmakuCatから別の名前

### ISSUE THREAD

**Issue by K93MSY** [K93MSY/DanmakuCat#14]
正直考え直してみたらマジで弾幕要素ないとおもっちゃった
Escape Cat
Cat Run Away
なんかほかにいいのあるかな
弾幕要素がないからプレイする人に「は？」って思われちゃいそう

**Comment by WatanabeMasaaki** [comment]
Cat Survival
キャッツサバイバル！

**Comment by WatanabeMasaaki** [comment]
Beat escaper
Beat survival
Music Boxer
Music Boxx
Beat Box
Beat Square
こんなもん？

**Comment by K93MSY** [comment]
CatはいれたかったのでSquare Cat Survivalにしました
